// jumper - the first real game content since 2012: a small jump-and-run.
//
// Boots the engine exactly like tools/player (SDL3 owns the window and event
// loop, Orkige::Engine renders into it via the externalWindowHandle path) and
// is the reference for how a game sits on top of the engine:
//
//   scene = data, app = behavior. samples/jumper/level1.oscene holds only
//   GameObjects + components (textured platform/crate meshes, static and
//   dynamic RigidBodies, the goal marker) - it opens, renders and edits in
//   the editor like any other scene. Everything player-specific (input,
//   jumping, respawn, win detection, camera) lives HERE, in JumperGame; the
//   app spawns the player object itself at runtime. A GameLogicComponent /
//   Lua-driven behavior layer that would move this INTO the scene is future
//   work (scripting).
//
// Assets: samples/jumper/media/*, generated by Util/make_jumper_assets.py
// (license-clean, stdlib-only). The PNG textures are EMBEDDED in the .glb
// binary chunks; OGRE's Codec_Assimp registers embedded images in the
// TextureManager and wires them into the imported materials, so no sidecar
// texture files are needed at runtime (the .png files exist for reference).
// All jumper meshes carry white COLOR_0, so the engine's shared unlit fix
// (vertex-colour tracking) leaves the textures intact.
//
// Gameplay tuning (the "feel" numbers, see JumperGame):
//   gravity (0,-20,0)  - ~2x earth, snappy platformer arcs
//   move speed 4.5 m/s - velocity-controlled (exponential approach, rate 12/s
//                        -> ~98% of target speed after 1/3 s), full air control
//   jump speed 8 m/s   - apex ~1.6 m after ~0.4 s, ~0.8 s total air time
//   kill plane y=-10   - falling below respawns at the start
//
// Controls: A/D or Left/Right move along the level (x), W/S or Up/Down dodge
// in depth (z - the level is 2.5D-ish but fully 3D, planar mode is OFF),
// SPACE jumps (grounded check via a short PhysicsWorld::castRay below the
// capsule), ESC quits. The capsule is kept upright by zeroing its angular
// velocity every frame (no rotation-lock DOFs are exposed yet).
//
// Modes / automation hooks:
//   jumper [scene.oscene]        play (default level: samples/jumper/level1.oscene)
//   jumper --write-level [path]  rebuild level1.oscene through SceneSerializer
//   ORKIGE_DEMO_FRAMES=N         exit 0 after N frames
//   ORKIGE_DEMO_SCREENSHOT=path  framebuffer dump at frame 55
//   ORKIGE_DEMO_WINDOW_SIZE=WxH  window size override (perf measurements)
//   ORKIGE_DEMO_FPS_LOG=1        log frame count / avg / p95 ms at exit
//   ORKIGE_JUMPER_SELFCHECK=1    scripted input run asserting textures loaded,
//                                movement, jump+landing, fall-respawn, the
//                                goal path and the fastgui HUD (widgets exist,
//                                title splash times out, win banner fires) -
//                                the jumper_selfcheck ctest test
//   ORKIGE_JUMPER_HUD_SCREENSHOT=path  (selfcheck only) framebuffer dump a few
//                                frames after the win, HUD banner visible
//
// HUD: engine_fastgui (the engine's own UiRenderer-based UI) with the generated
// atlas media/fastgui_default.{ogui,png} - see the shared JumperHud.h (also
// compiled by the jumper-native project module) and Util/make_fastgui_atlas.py.
#include <SDL3/SDL.h>
#include <engine_graphic/Engine.h>
#include <engine_render/RenderSystem.h>
#include <engine_render/RenderWorld.h>
#include <engine_render/RenderNode.h>
#include <engine_render/RenderCamera.h>
#include <engine_render/MeshInstance.h>
#include <engine_fastgui/FastGuiManager.h>
#include <engine_fastgui/FastGuiLabel.h>
#include <engine_fastgui/FastGuiProgressBar.h>
#include <engine_gocomponent/TransformComponent.h>
#include <engine_gocomponent/ModelComponent.h>
#include <engine_gocomponent/RigidBodyComponent.h>
#include <engine_physic/PhysicsWorld.h>
#include <engine_input/InputManager.h>
#include <engine_util/FrameStatsUtil.h>
#include <engine_util/StringUtil.h>
#include <core_game/GameObjectManager.h>
#include <core_game/SceneSerializer.h>
#include <core_util/StringUtil.h>
#include <core_util/Timer.h>
#include <core_event/GlobalEventManager.h>
#include <core_script/ScriptRuntime.h>

#include "JumperHud.h"
#include "JumperLogic.h"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

using Orkige::optr;
using Orkige::woptr;

extern "C" void* orkige_native_window_handle(SDL_Window* window);

namespace
{

//! keyboard state fed by the engine input pipeline (SDL event ->
//! InputManager::injectEvent -> KeyPressed/KeyReleasedEvent -> here); the
//! gameplay code never touches raw SDL
struct JumperInput
{
	bool left = false;
	bool right = false;
	bool forward = false;	//!< into the screen (-z)
	bool back = false;		//!< toward the camera (+z)
	float jumpBuffer = 0.0f;	//!< seconds a queued jump press stays valid
	bool quitRequested = false;

	//! how long a SPACE press waits for the ground (jump buffering)
	static constexpr float JUMP_BUFFER_SECONDS = 0.12f;

	bool onKeyPressed(Orkige::Event const& event)
	{
		switch (event.getDataPtr<Orkige::KeyEventData>()->key)
		{
		case Orkige::KeyEventData::KC_A:
		case Orkige::KeyEventData::KC_LEFT:		left = true; break;
		case Orkige::KeyEventData::KC_D:
		case Orkige::KeyEventData::KC_RIGHT:	right = true; break;
		case Orkige::KeyEventData::KC_W:
		case Orkige::KeyEventData::KC_UP:		forward = true; break;
		case Orkige::KeyEventData::KC_S:
		case Orkige::KeyEventData::KC_DOWN:		back = true; break;
		case Orkige::KeyEventData::KC_SPACE:
			jumpBuffer = JUMP_BUFFER_SECONDS;
			break;
		case Orkige::KeyEventData::KC_ESCAPE:
			quitRequested = true;
			break;
		default: break;
		}
		return false;
	}
	bool onKeyReleased(Orkige::Event const& event)
	{
		switch (event.getDataPtr<Orkige::KeyEventData>()->key)
		{
		case Orkige::KeyEventData::KC_A:
		case Orkige::KeyEventData::KC_LEFT:		left = false; break;
		case Orkige::KeyEventData::KC_D:
		case Orkige::KeyEventData::KC_RIGHT:	right = false; break;
		case Orkige::KeyEventData::KC_W:
		case Orkige::KeyEventData::KC_UP:		forward = false; break;
		case Orkige::KeyEventData::KC_S:
		case Orkige::KeyEventData::KC_DOWN:		back = false; break;
		default: break;
		}
		return false;
	}
};

// ModelComponent does not serialize material tweaks (yet) - re-apply the
// shared unlit render state after a scene load, exactly like tools/player.
// The jumper meshes carry white COLOR_0, so vertex-colour tracking keeps
// their textures intact (white x texture = texture).
void applyUnlitFixToLoadedModels(Orkige::GameObjectManager& gameObjectManager)
{
	for (auto const& [id, gameObject] : gameObjectManager.getGameObjects())
	{
		if (!gameObject->hasComponent<Orkige::ModelComponent>())
		{
			continue;
		}
		optr<Orkige::MeshInstance> mesh =
			gameObject->getComponentPtr<Orkige::ModelComponent>()
				->getMeshInstance();
		if (mesh)
		{
			mesh->setVertexColourUnlit();
		}
	}
}

//! the jump-and-run gameplay: owns the player object and the per-frame rules
//! (movement, jump, respawn, win, camera). Reads scene data (the goal marker)
//! from the loaded level but never stores behavior in it.
class JumperGame
{
public:
	//--- tuning (the "feel" numbers) --------------------------------------
	static constexpr float MOVE_SPEED = 4.5f;		//!< target run speed m/s
	static constexpr float ACCEL_RATE = 12.0f;		//!< velocity approach rate 1/s
	static constexpr float JUMP_SPEED = 8.0f;		//!< take-off velocity m/s
	static constexpr float GRAVITY_Y = -20.0f;		//!< snappy platformer gravity
	static constexpr float KILL_PLANE_Y = -10.0f;	//!< fall-out respawn line
	static constexpr float GOAL_RADIUS = 1.5f;		//!< win distance to the marker
	static constexpr float CAMERA_RATE = 5.0f;		//!< camera follow approach rate
	//--- player capsule (matches jumper_player.glb) ------------------------
	static constexpr float CAPSULE_HALF_HEIGHT = 0.25f;	//!< cylinder part
	static constexpr float CAPSULE_RADIUS = 0.35f;

	JumperGame(Orkige::GameObjectManager& gameObjectManager,
		Orkige::PhysicsWorld& physicsWorld,
		optr<Orkige::RenderNode> const& cameraNode)
		: mGameObjectManager(gameObjectManager), mPhysicsWorld(physicsWorld),
		mCameraNode(cameraNode)
	{
	}

	//! create the player GameObject (app-owned - NOT part of level1.oscene)
	bool spawnPlayer()
	{
		optr<Orkige::GameObject> player =
			mGameObjectManager.createGameObject("Player").lock();
		if (!player ||
			!player->addComponent<Orkige::TransformComponent>() ||
			!player->addComponent<Orkige::ModelComponent>() ||
			!player->addComponent<Orkige::RigidBodyComponent>())
		{
			return false;
		}
		mPlayerTransform = player->getComponentPtr<Orkige::TransformComponent>();
		mPlayerBody = player->getComponentPtr<Orkige::RigidBodyComponent>();
		Orkige::ModelComponent* model =
			player->getComponentPtr<Orkige::ModelComponent>();
		model->loadModel("jumper_player.glb");
		if (!model->getMeshInstance())
		{
			return false;
		}
		model->getMeshInstance()->setVertexColourUnlit();
		mPlayerTransform->setPosition(mSpawnPosition);
		mPlayerBody->setBodyType(Orkige::PhysicsWorld::BT_DYNAMIC);
		mPlayerBody->setCapsuleShape(CAPSULE_HALF_HEIGHT, CAPSULE_RADIUS);
		mPlayerBody->setMass(1.0f);
		// low friction: the player is velocity-controlled, high friction would
		// glue the capsule to walls and platform edges
		mPlayerBody->setFriction(0.2f);
		mPlayerBody->setRestitution(0.0f);
		return true;
	}

	//! read the goal marker's position from the loaded scene (scene = data)
	void findGoal()
	{
		optr<Orkige::GameObject> goal =
			mGameObjectManager.getGameObject("Goal").lock();
		if (goal && goal->hasComponent<Orkige::TransformComponent>())
		{
			mGoalPosition = goal->getComponentPtr<
				Orkige::TransformComponent>()->getPosition();
			mHasGoal = true;
		}
		else
		{
			SDL_Log("jumper: no 'Goal' object in the scene - win check disabled");
		}
	}

	//! run one gameplay frame; call AFTER PhysicsWorld/GameObjectManager update
	void update(float deltaTime, JumperInput& input)
	{
		if (!mPlayerBody || !mPlayerBody->hasBody())
		{
			return;	// body is created lazily on the first component update
		}
		const Orkige::Vec3 position = mPlayerTransform->getPosition();

		// grounded: short ray just below the capsule (see JumperLogic for why
		// it must start OUTSIDE the capsule); never accept a self-hit
		const Orkige::JumperLogic::GroundProbe probe =
			Orkige::JumperLogic::makeGroundProbe(position,
				CAPSULE_HALF_HEIGHT, CAPSULE_RADIUS);
		Orkige::Vec3 hitPosition;
		Orkige::PhysicsWorld::BodyId hitBodyId =
			Orkige::PhysicsWorld::INVALID_BODY_ID;
		mGrounded = mPhysicsWorld.castRay(probe.origin, probe.direction,
			probe.maxDistance, hitPosition, hitBodyId) &&
			hitBodyId != mPlayerBody->getBodyId();

		// velocity control: exponential approach to the input direction, the
		// same in the air (full air control - tight, forgiving feel)
		const float inputX = (input.right ? 1.0f : 0.0f) - (input.left ? 1.0f : 0.0f);
		const float inputZ = (input.back ? 1.0f : 0.0f) - (input.forward ? 1.0f : 0.0f);
		Orkige::Vec3 velocity = mPlayerBody->getLinearVelocity();
		velocity.x = Orkige::JumperLogic::approach(velocity.x,
			inputX * MOVE_SPEED, ACCEL_RATE, deltaTime);
		velocity.z = Orkige::JumperLogic::approach(velocity.z,
			inputZ * MOVE_SPEED, ACCEL_RATE, deltaTime);

		// buffered jump: a SPACE press up to 0.12s before landing still jumps
		input.jumpBuffer = std::max(0.0f, input.jumpBuffer - deltaTime);
		if (mGrounded && input.jumpBuffer > 0.0f)
		{
			velocity.y = JUMP_SPEED;
			input.jumpBuffer = 0.0f;
			mGrounded = false;
		}
		mPlayerBody->setLinearVelocity(velocity);

		// keep the capsule upright: no rotation-lock DOFs are exposed through
		// PhysicsWorld yet (planar mode would also lock translation), so kill
		// contact-induced spin every frame and re-align when friction still
		// managed to tilt the capsule
		mPlayerBody->setAngularVelocity(Orkige::Vec3::ZERO);
		const Orkige::Quat orientation = mPlayerTransform->getOrientation();
		if (std::abs(orientation.w) < 0.9995f)
		{
			mPhysicsWorld.setBodyTransform(mPlayerBody->getBodyId(), position,
				Orkige::Quat::IDENTITY);
		}

		// fell out of the level?
		if (Orkige::JumperLogic::isBelowKillPlane(position.y, KILL_PLANE_Y))
		{
			SDL_Log("jumper: fell out of the level - respawning");
			respawn();
			return;
		}
		// reached the buddy at the end?
		if (mHasGoal && Orkige::JumperLogic::reachedGoal(position,
			mGoalPosition, GOAL_RADIUS))
		{
			++mWinCount;
			SDL_Log("jumper: WIN! you reached your buddy (win #%d) - "
				"respawning for another round", mWinCount);
			respawn();
			return;
		}

		// smooth camera follow, looking slightly ahead of the player
		const Orkige::Vec3 cameraTarget = position + CAMERA_OFFSET;
		Orkige::Vec3 cameraPosition = mCameraNode->getPosition();
		cameraPosition.x = Orkige::JumperLogic::approach(cameraPosition.x,
			cameraTarget.x, CAMERA_RATE, deltaTime);
		cameraPosition.y = Orkige::JumperLogic::approach(cameraPosition.y,
			cameraTarget.y, CAMERA_RATE, deltaTime);
		cameraPosition.z = Orkige::JumperLogic::approach(cameraPosition.z,
			cameraTarget.z, CAMERA_RATE, deltaTime);
		mCameraNode->setPosition(cameraPosition);
		mCameraNode->lookAt(position + CAMERA_LOOK_AHEAD,
			Orkige::RenderNode::TS_WORLD);
	}

	//! put the player back at the start (teleport + kill all momentum)
	void respawn()
	{
		++mRespawnCount;
		teleportPlayer(mSpawnPosition);
	}

	//! teleport the player body (also used by the selfcheck script)
	void teleportPlayer(Orkige::Vec3 const& position)
	{
		if (!mPlayerBody || !mPlayerBody->hasBody())
		{
			return;
		}
		mPhysicsWorld.setBodyTransform(mPlayerBody->getBodyId(), position,
			Orkige::Quat::IDENTITY);
		mPlayerBody->setLinearVelocity(Orkige::Vec3::ZERO);
		mPlayerBody->setAngularVelocity(Orkige::Vec3::ZERO);
		mPlayerTransform->setPosition(position);
	}

	Orkige::Vec3 getPlayerPosition() const
	{
		return mPlayerTransform ? mPlayerTransform->getPosition()
			: Orkige::Vec3::ZERO;
	}
	Orkige::Vec3 const& getSpawnPosition() const { return mSpawnPosition; }
	Orkige::Vec3 const& getGoalPosition() const { return mGoalPosition; }
	bool hasGoal() const { return mHasGoal; }
	//! progress toward the goal along the level axis (0 = spawn, 1 = goal)
	float getGoalProgress() const
	{
		if (!mHasGoal || mGoalPosition.x <= mSpawnPosition.x)
		{
			return 0.0f;
		}
		return (getPlayerPosition().x - mSpawnPosition.x) /
			(mGoalPosition.x - mSpawnPosition.x);
	}
	bool isGrounded() const { return mGrounded; }
	int getRespawnCount() const { return mRespawnCount; }
	int getWinCount() const { return mWinCount; }
	Orkige::RigidBodyComponent* getPlayerBody() const { return mPlayerBody; }

private:
	static inline const Orkige::Vec3 CAMERA_OFFSET =
		Orkige::Vec3(0.0f, 2.2f, 8.0f);
	static inline const Orkige::Vec3 CAMERA_LOOK_AHEAD =
		Orkige::Vec3(1.5f, 0.8f, 0.0f);

	Orkige::GameObjectManager&		mGameObjectManager;
	Orkige::PhysicsWorld&			mPhysicsWorld;
	optr<Orkige::RenderNode>		mCameraNode;
	Orkige::TransformComponent*		mPlayerTransform = nullptr;
	Orkige::RigidBodyComponent*		mPlayerBody = nullptr;
	Orkige::Vec3					mSpawnPosition = Orkige::Vec3(0.0f, 1.0f, 0.0f);
	Orkige::Vec3					mGoalPosition = Orkige::Vec3::ZERO;
	bool							mHasGoal = false;
	bool							mGrounded = false;
	int								mRespawnCount = 0;
	int								mWinCount = 0;
};

//--- level construction (the --write-level mode) ---------------------------

//! create one visible object: Transform + Model (+ optional RigidBody)
bool makeLevelObject(Orkige::GameObjectManager& gameObjectManager,
	std::string const& id, std::string const& mesh,
	Orkige::Vec3 const& position, Orkige::Vec3 const& scale,
	bool withBody, Orkige::PhysicsWorld::BodyType bodyType, float friction)
{
	optr<Orkige::GameObject> gameObject =
		gameObjectManager.createGameObject(id).lock();
	if (!gameObject ||
		!gameObject->addComponent<Orkige::TransformComponent>() ||
		!gameObject->addComponent<Orkige::ModelComponent>())
	{
		return false;
	}
	Orkige::TransformComponent* transform =
		gameObject->getComponentPtr<Orkige::TransformComponent>();
	transform->setPosition(position);
	transform->setScale(scale);
	gameObject->getComponentPtr<Orkige::ModelComponent>()->loadModel(mesh);
	if (withBody)
	{
		if (!gameObject->addComponent<Orkige::RigidBodyComponent>())
		{
			return false;
		}
		Orkige::RigidBodyComponent* rigidBody =
			gameObject->getComponentPtr<Orkige::RigidBodyComponent>();
		rigidBody->setBodyType(bodyType);
		// the meshes are unit cubes: collision halfExtents = scale * 0.5
		// (RigidBodyComponent does not follow the transform scale)
		rigidBody->setBoxShape(scale * 0.5f);
		rigidBody->setMass(1.0f);
		rigidBody->setFriction(friction);
		rigidBody->setRestitution(0.0f);
	}
	return true;
}

//! @brief build level1: 9 platforms rising along +x (gaps 1.25-2.0, rises up
//! to 1.0 - comfortably inside the 1.6m jump apex), crates to knock around
//! and the goal buddy at the end. Pure scene DATA - saved via SceneSerializer
//! and checked in; the jumper app itself only ever LOADS the .oscene.
bool buildLevel(Orkige::GameObjectManager& gameObjectManager)
{
	struct PlatformDef
	{
		const char* id;
		Orkige::Vec3 position;
		Orkige::Vec3 scale;
	};
	// top surface = position.y + scale.y / 2
	const PlatformDef platforms[] = {
		{ "Platform1", {  0.0f, -0.25f, 0.0f }, { 4.0f, 0.5f, 4.0f } },
		{ "Platform2", {  5.0f,  0.25f, 0.0f }, { 3.0f, 0.5f, 3.0f } },
		{ "Platform3", {  9.5f,  1.00f, 0.0f }, { 3.0f, 0.5f, 3.0f } },
		{ "Platform4", { 14.0f,  0.25f, 0.0f }, { 2.5f, 0.5f, 3.0f } },
		{ "Platform5", { 18.0f,  1.25f, 0.0f }, { 2.5f, 0.5f, 3.0f } },
		{ "Platform6", { 22.5f,  2.25f, 0.0f }, { 2.5f, 0.5f, 3.0f } },
		{ "Platform7", { 27.0f,  0.75f, 0.0f }, { 3.0f, 0.5f, 3.0f } },
		{ "Platform8", { 31.5f,  1.75f, 0.0f }, { 2.5f, 0.5f, 3.0f } },
		{ "Platform9", { 36.0f,  0.75f, 0.0f }, { 4.0f, 0.5f, 4.0f } },
	};
	for (PlatformDef const& platform : platforms)
	{
		if (!makeLevelObject(gameObjectManager, platform.id,
			"jumper_platform.glb", platform.position, platform.scale,
			true, Orkige::PhysicsWorld::BT_STATIC, 0.9f))
		{
			return false;
		}
	}
	// dynamic crates resting on platforms (top + 0.3)
	const PlatformDef crates[] = {
		{ "Crate1", {  9.5f, 1.55f,  0.9f }, { 0.6f, 0.6f, 0.6f } },
		{ "Crate2", { 27.0f, 1.30f, -0.7f }, { 0.6f, 0.6f, 0.6f } },
		{ "Crate3", { 27.0f, 1.90f, -0.7f }, { 0.6f, 0.6f, 0.6f } },
	};
	for (PlatformDef const& crate : crates)
	{
		if (!makeLevelObject(gameObjectManager, crate.id, "jumper_crate.glb",
			crate.position, crate.scale, true,
			Orkige::PhysicsWorld::BT_DYNAMIC, 0.6f))
		{
			return false;
		}
	}
	// the goal: a buddy capsule waiting on the last platform (no rigid body -
	// it is a marker; the app's win check reads its position)
	return makeLevelObject(gameObjectManager, "Goal", "jumper_player.glb",
		Orkige::Vec3(37.0f, 1.6f, 0.0f), Orkige::Vec3(1.0f, 1.0f, 1.0f),
		false, Orkige::PhysicsWorld::BT_STATIC, 0.0f);
}

//! does sub-mesh 0 of a ModelComponent's mesh sample a texture - 1/0, or -1
//! when there is no loaded model (the selfcheck's "the textures actually
//! loaded" probe, now through the facade MeshInstance)
int textureUnitCount(Orkige::GameObjectManager& gameObjectManager,
	std::string const& id)
{
	optr<Orkige::GameObject> gameObject =
		gameObjectManager.getGameObject(id).lock();
	if (!gameObject || !gameObject->hasComponent<Orkige::ModelComponent>())
	{
		return -1;
	}
	optr<Orkige::MeshInstance> mesh =
		gameObject->getComponentPtr<Orkige::ModelComponent>()
			->getMeshInstance();
	if (!mesh || mesh->getNumSubMeshes() == 0)
	{
		return -1;
	}
	return mesh->subMeshHasTexture(0) ? 1 : 0;
}

//! push a synthetic key event through the SDL queue (same pattern as the
//! demo's ORKIGE_DEMO_SYNTH_ESC) - the loop's SDL_PollEvent feeds it into
//! InputManager::injectEvent, so scripted input takes the REAL input path
void pushKeyEvent(SDL_Scancode scancode, SDL_Keycode key, bool down)
{
	SDL_Event event{};
	event.type = down ? SDL_EVENT_KEY_DOWN : SDL_EVENT_KEY_UP;
	event.key.scancode = scancode;
	event.key.key = key;
	event.key.down = down;
	SDL_PushEvent(&event);
}

} // namespace

int main(int argc, char** argv)
{
	// argument handling: optional scene path, or --write-level [path]
	std::string scenePath = ORKIGE_JUMPER_LEVEL_FILE;
	bool writeLevel = false;
	for (int argIndex = 1; argIndex < argc; ++argIndex)
	{
		if (std::strcmp(argv[argIndex], "--write-level") == 0)
		{
			writeLevel = true;
		}
		else if (argv[argIndex][0] != '-')
		{
			scenePath = argv[argIndex];
		}
		else
		{
			SDL_Log("usage: jumper [scene.oscene] [--write-level]");
			return 1;
		}
	}

	if (!SDL_Init(SDL_INIT_VIDEO))
	{
		SDL_Log("SDL_Init failed: %s", SDL_GetError());
		return 1;
	}
	// ORKIGE_DEMO_WINDOW_SIZE=WxH: window size override for automated
	// performance measurements (default stays 1280x720)
	int windowWidth = 1280;
	int windowHeight = 720;
	if (const char* windowSize = std::getenv("ORKIGE_DEMO_WINDOW_SIZE"))
	{
		int width = 0;
		int height = 0;
		if (std::sscanf(windowSize, "%dx%d", &width, &height) == 2 &&
			width > 0 && height > 0)
		{
			windowWidth = width;
			windowHeight = height;
		}
	}
	SDL_Window* window = SDL_CreateWindow("Orkige Jumper",
		windowWidth, windowHeight, 0);
	if (!window)
	{
		SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
		return 1;
	}
	// SDL may have clamped the request to the usable display bounds
	SDL_GetWindowSize(window, &windowWidth, &windowHeight);

	int exitCode = 0;
	{
		// engine singletons normally created by Orkige::Application; the same
		// boot set as the demo/player/editor
		Orkige::Timer::initialise();
		Orkige::GlobalEventManager eventManager;
		Orkige::ScriptRuntime scriptRuntime;
		init_module_orkige_core();

		// automation hooks (read before engine setup - they gate the vsync
		// and frame-pacing decisions below): ORKIGE_DEMO_FRAMES frame-limits
		// the run, ORKIGE_JUMPER_SELFCHECK runs the scripted verification
		unsigned long frameLimit = 0;
		if (const char* demoFrames = std::getenv("ORKIGE_DEMO_FRAMES"))
		{
			frameLimit = std::strtoul(demoFrames, nullptr, 10);
		}
		const bool selfCheck =
			(std::getenv("ORKIGE_JUMPER_SELFCHECK") != nullptr);
		// automated runs (ctest, screenshots, measurements) render as fast as
		// the machine allows; a HUMAN run gets vsync so the game neither spins
		// uncapped nor tears
		const bool automatedRun = selfCheck || frameLimit != 0;

		// ORKIGE_SANCTIONED_OGRE_BEGIN(classic-boot) - lint gate, see Util/ogre_containment.json
		// --- classic boot block (sanctioned raw-Ogre corner, see
		// Docs/render-abstraction.md "App boot"): Engine construction/config
		// and the RTSS-internal media registration stay classic plumbing;
		// everything after Engine::setup talks to the engine_render facade.
		Orkige::Engine engine(Ogre::SMT_DEFAULT,
			Orkige::StringUtil::BLANK, Orkige::StringUtil::BLANK,
			Orkige::StringUtil::BLANK, "jumper.log");
		engine.setCustomWindowParam("width",
			Orkige::StringUtil::Converter::toString(windowWidth));
		engine.setCustomWindowParam("height",
			Orkige::StringUtil::Converter::toString(windowHeight));
		if (!automatedRun)
		{
			engine.setCustomWindowParam("vsync", "true");
		}
		if (const char* renderSystemEnv = std::getenv("ORKIGE_RENDERSYSTEM"))
		{
			engine.setPreferredRenderSystem(renderSystemEnv);
		}

		// RTSS shader library (backend-internal media, needed before setup -
		// classic bootstrap business, not a facade call)
		Ogre::ResourceGroupManager::getSingleton().addResourceLocation(
			ORKIGE_JUMPER_MEDIA_DIR "/Main", "FileSystem", Ogre::RGN_INTERNAL);
		Ogre::ResourceGroupManager::getSingleton().addResourceLocation(
			ORKIGE_JUMPER_MEDIA_DIR "/RTShaderLib", "FileSystem",
			Ogre::RGN_INTERNAL);

		if (!engine.setup("Orkige Jumper", Orkige::Engine::SHOW_NEVER,
			Orkige::StringUtil::Converter::toString(
				reinterpret_cast<size_t>(orkige_native_window_handle(window)))))
		{
			SDL_Log("Engine::setup failed");
			return 1;
		}
		// ORKIGE_SANCTIONED_OGRE_END
		// --- end of the classic boot block: from here on the game talks to
		// the renderer through the engine_render facade exclusively
		Orkige::RenderSystem* render = Orkige::RenderSystem::get();
		Orkige::RenderWorld* world = render->getWorld();

		// the jumper assets (textured .glb meshes) through the facade
		render->addResourceLocation(ORKIGE_JUMPER_ASSET_DIR);
		render->initialiseResourceGroups();

		// the window camera on a facade rig (createDefaultCameraAndViewport
		// successor); the fixed yaw axis keeps the per-frame follow-camera
		// lookAt roll-free - the selfcheck asserts exactly that
		optr<Orkige::RenderCamera> camera = world->createCamera("jumper.camera");
		optr<Orkige::RenderNode> cameraNode =
			world->createNode("jumper.cameraNode");
		cameraNode->setFixedYawAxis(true);
		camera->attachTo(cameraNode);
		render->showCameraOnWindow(camera);

		world->setAmbientLight(Orkige::Color(0.2f, 0.2f, 0.2f));
		// a friendly sky instead of the void
		render->setWindowBackgroundColour(Orkige::Color(0.53f, 0.75f, 0.94f));

		// shared primitives scenes may reference (same as player/editor):
		// the procedural cube mesh + its unlit "VertexColour" material
		world->createVertexColourCubeMesh();

		// input pipeline: the poll loop feeds every SDL event into the
		// InputManager, which triggers the Orkige input events JumperInput
		// listens to - gameplay code never sees raw SDL
		Orkige::InputManager inputManager;
		JumperInput input;
		optr<Orkige::EventListener> keyPressedListener =
			Orkige::GlobalEventManager::getSingleton().bind(
				Orkige::InputManager::KeyPressedEvent,
				&JumperInput::onKeyPressed, &input);
		optr<Orkige::EventListener> keyReleasedListener =
			Orkige::GlobalEventManager::getSingleton().bind(
				Orkige::InputManager::KeyReleasedEvent,
				&JumperInput::onKeyReleased, &input);

		init_module_orkige_engine();
		Orkige::GameObjectManager gameObjectManager;
		Orkige::PhysicsWorld physicsWorld;

		if (writeLevel)
		{
			// generator mode: build the level DATA and save it through the
			// serializer - this is how samples/jumper/level1.oscene is made
			if (!buildLevel(gameObjectManager))
			{
				SDL_Log("jumper: FAILED - level construction");
				return 1;
			}
			if (!Orkige::SceneSerializer::saveScene(scenePath,
				gameObjectManager))
			{
				SDL_Log("jumper: FAILED - could not save '%s'",
					scenePath.c_str());
				return 1;
			}
			SDL_Log("jumper: level written to '%s' (%zu GameObjects)",
				scenePath.c_str(), gameObjectManager.getGameObjects().size());
			SDL_DestroyWindow(window);
			SDL_Quit();
			return 0;
		}

		if (!Orkige::SceneSerializer::loadScene(scenePath, gameObjectManager))
		{
			SDL_Log("jumper: FAILED - could not load scene '%s'",
				scenePath.c_str());
			return 1;
		}
		applyUnlitFixToLoadedModels(gameObjectManager);
		SDL_Log("jumper: level '%s' loaded (%zu GameObjects)",
			scenePath.c_str(), gameObjectManager.getGameObjects().size());

		if (!physicsWorld.init())
		{
			SDL_Log("jumper: FAILED - PhysicsWorld::init failed");
			return 1;
		}
		physicsWorld.setGravity(Orkige::Vec3(0.0f, JumperGame::GRAVITY_Y, 0.0f));

		JumperGame game(gameObjectManager, physicsWorld, cameraNode);
		if (!game.spawnPlayer())
		{
			SDL_Log("jumper: FAILED - player creation");
			return 1;
		}
		game.findGoal();
		cameraNode->setPosition(game.getSpawnPosition() +
			Orkige::Vec3(0.0f, 2.2f, 8.0f));
		cameraNode->lookAt(game.getSpawnPosition(),
			Orkige::RenderNode::TS_WORLD);

		// the HUD (engine_fastgui): title splash, controls hint, win banner,
		// distance-to-goal progress bar - see the shared JumperHud.h
		unsigned int hudWidth = 0;
		unsigned int hudHeight = 0;
		render->getWindowSize(hudWidth, hudHeight);
		Orkige::JumperHud hud(static_cast<int>(hudWidth),
			static_cast<int>(hudHeight));
		int hudLastWinCount = game.getWinCount();

		// frame-time statistics: the ORKIGE_DEMO_FPS_LOG measurement hook and
		// the one-time "this build is too slow to play" hint
		Orkige::FrameStatsUtil frameStats;

		// --- ORKIGE_JUMPER_SELFCHECK=1: scripted verification run ----------
		// Injects synthetic SDL key events (the demo's SYNTH_ESC pattern) so
		// every input goes through the real pipeline, then asserts:
		//   frame  5  the textured meshes loaded (texture units on the
		//             platform + player materials)
		//   10..30    hold RIGHT  -> frame 45: the player moved +x
		//   frame 60  press SPACE -> the player rises >0.8m and is grounded
		//             again within 120 frames
		//   then      teleport into the first gap -> falls below y=-10 ->
		//             respawns at the start
		//   then      teleport in front of the goal -> win fires -> respawn
		// Any missed deadline exits non-zero; measured values are logged.
		// (selfCheck itself is read above, before the engine window exists.)
		enum class CheckPhase
		{
			Script,			// fixed-frame part (textures, move, jump press)
			WaitLanding,	// jump flight until grounded again
			WaitRespawn,	// falling in the gap until the respawn happened
			WaitWin,		// walking distance of the goal until win fires
			WaitBanner,		// HUD: win banner visible + rendered (screenshot)
			Done
		};
		CheckPhase checkPhase = CheckPhase::Script;
		float checkStartX = 0.0f;
		float checkMovedX = 0.0f;
		float checkJumpStartY = 0.0f;
		float checkMaxRise = 0.0f;
		unsigned long checkJumpFrame = 0;
		unsigned long checkLandedFrame = 0;
		unsigned long checkPhaseDeadline = 0;
		int checkBaseRespawns = 0;
		int checkBaseWins = 0;
		float checkMaxProgress = 0.0f;	//!< peak HUD progress on the goal walk
		int checkProgressFrames = 0;	//!< frames with a near-full HUD bar
		bool checkFailed = false;
		auto checkFail = [&](std::string const& what)
		{
			SDL_Log("jumper: SELFCHECK FAILED - %s (frame dependent state: "
				"pos %.2f/%.2f/%.2f grounded=%d respawns=%d wins=%d)",
				what.c_str(), game.getPlayerPosition().x,
				game.getPlayerPosition().y, game.getPlayerPosition().z,
				static_cast<int>(game.isGrounded()), game.getRespawnCount(),
				game.getWinCount());
			checkFailed = true;
		};

		bool running = true;
		unsigned long frameCount = 0;
		std::chrono::steady_clock::time_point lastFrameTime =
			std::chrono::steady_clock::now();
		while (running)
		{
			SDL_Event event;
			while (SDL_PollEvent(&event))
			{
				if (event.type == SDL_EVENT_QUIT)
				{
					running = false;
				}
				inputManager.injectEvent(event);
			}
			if (input.quitRequested)
			{
				running = false;
			}

			// measured frame dt. Automated (frame-scripted) runs keep the
			// historical 1/60 floor so headless frames accumulate simulated
			// time; a HUMAN run uses the real dt - flooring it at 1/60 made
			// gameplay run FASTER than real time whenever rendering beat 60
			// fps (physics stepped its fixed 1/60 tick once per rendered
			// frame). The 0.1 cap stays: it avoids the catch-up spiral after
			// a stall, at the honest price of slow motion below 10 fps.
			const std::chrono::steady_clock::time_point frameTime =
				std::chrono::steady_clock::now();
			float deltaTime = std::chrono::duration<float>(
				frameTime - lastFrameTime).count();
			lastFrameTime = frameTime;
			frameStats.addFrame(deltaTime);
			frameStats.maybeWarnSlow("jumper");
			deltaTime = std::clamp(deltaTime,
				automatedRun ? 1.0f / 60.0f : 0.0001f, 0.1f);

			physicsWorld.update(deltaTime);
			gameObjectManager.update(deltaTime);	// body creation + pose sync
			game.update(deltaTime, input);			// the gameplay rules

			// HUD: win banner on a new win, then timers + progress bar
			if (game.getWinCount() > hudLastWinCount)
			{
				hudLastWinCount = game.getWinCount();
				hud.showWinBanner();
			}
			hud.update(deltaTime, game.getGoalProgress());

			if (!render->renderOneFrame())
			{
				running = false;
			}
			++frameCount;

			if (frameCount == 55)
			{
				// ORKIGE_DEMO_SCREENSHOT: the player stands mid-level on the
				// textured start platform, the level stretching to the right
				if (const char* shotPath = std::getenv("ORKIGE_DEMO_SCREENSHOT"))
				{
					render->saveWindowContents(shotPath);
				}
			}

			// --- selfcheck script ------------------------------------------
			if (selfCheck && !checkFailed && checkPhase == CheckPhase::Script)
			{
				if (frameCount == 5)
				{
					const int platformUnits =
						textureUnitCount(gameObjectManager, "Platform1");
					const int crateUnits =
						textureUnitCount(gameObjectManager, "Crate1");
					const int playerUnits =
						textureUnitCount(gameObjectManager, "Player");
					SDL_Log("jumper: selfcheck textures - platform=%d crate=%d "
						"player=%d texture units", platformUnits, crateUnits,
						playerUnits);
					if (platformUnits < 1 || crateUnits < 1 || playerUnits < 1)
					{
						checkFail("textured meshes did not load with textures");
					}
					// HUD boot: FastGuiManager loaded the generated atlas and
					// all four widgets exist; the title splash is showing
					SDL_Log("jumper: selfcheck hud - widgets=%d title=%d "
						"banner=%d progress=%.0f%%",
						static_cast<int>(hud.widgetsExist()),
						static_cast<int>(hud.isTitleVisible()),
						static_cast<int>(hud.isWinBannerVisible()),
						hud.getProgress());
					if (!hud.widgetsExist())
					{
						checkFail("HUD widgets missing after FastGuiManager boot");
					}
					else if (!hud.isTitleVisible())
					{
						checkFail("HUD title not visible at start");
					}
					else if (hud.isWinBannerVisible())
					{
						checkFail("HUD win banner visible before any win");
					}
				}
				if (frameCount == 10)
				{
					checkStartX = game.getPlayerPosition().x;
					pushKeyEvent(SDL_SCANCODE_RIGHT, SDLK_RIGHT, true);
				}
				if (frameCount == 30)
				{
					pushKeyEvent(SDL_SCANCODE_RIGHT, SDLK_RIGHT, false);
				}
				if (frameCount == 45)
				{
					checkMovedX = game.getPlayerPosition().x - checkStartX;
					SDL_Log("jumper: selfcheck move - +x %.3f m after 20 "
						"frames of RIGHT (target speed %.1f m/s)",
						checkMovedX, JumperGame::MOVE_SPEED);
					if (checkMovedX < 0.6f)
					{
						checkFail("player did not move right under input");
					}
				}
				if (frameCount == 60)
				{
					if (!game.isGrounded())
					{
						checkFail("player not grounded before the jump");
					}
					checkJumpStartY = game.getPlayerPosition().y;
					checkJumpFrame = frameCount;
					checkMaxRise = 0.0f;
					pushKeyEvent(SDL_SCANCODE_SPACE, SDLK_SPACE, true);
					checkPhase = CheckPhase::WaitLanding;
					checkPhaseDeadline = frameCount + 120;
				}
			}
			else if (selfCheck && !checkFailed &&
				checkPhase == CheckPhase::WaitLanding)
			{
				checkMaxRise = std::max(checkMaxRise,
					game.getPlayerPosition().y - checkJumpStartY);
				if (frameCount == checkJumpFrame + 5)
				{
					pushKeyEvent(SDL_SCANCODE_SPACE, SDLK_SPACE, false);
				}
				// give take-off a few frames before accepting "grounded again"
				if (frameCount > checkJumpFrame + 10 && game.isGrounded())
				{
					checkLandedFrame = frameCount;
					SDL_Log("jumper: selfcheck jump - rise %.3f m (apex target "
						"%.2f), landed %lu frames after take-off",
						checkMaxRise, JumperGame::JUMP_SPEED *
						JumperGame::JUMP_SPEED / (2.0f * -JumperGame::GRAVITY_Y),
						checkLandedFrame - checkJumpFrame);
					if (checkMaxRise < 0.8f)
					{
						checkFail("jump did not raise the player");
					}
					else
					{
						// drop the player into the first gap: no ground below,
						// it must fall past the kill plane and respawn
						checkBaseRespawns = game.getRespawnCount();
						game.teleportPlayer(Orkige::Vec3(2.75f, 1.5f, 0.0f));
						checkPhase = CheckPhase::WaitRespawn;
						checkPhaseDeadline = frameCount + 300;
					}
				}
				else if (frameCount >= checkPhaseDeadline)
				{
					checkFail("player never landed after the jump");
				}
			}
			else if (selfCheck && !checkFailed &&
				checkPhase == CheckPhase::WaitRespawn)
			{
				if (game.getRespawnCount() > checkBaseRespawns)
				{
					const float spawnDistance = game.getPlayerPosition()
						.distance(game.getSpawnPosition());
					SDL_Log("jumper: selfcheck respawn - fell off, back %.3f m "
						"from the spawn point after respawn #%d",
						spawnDistance, game.getRespawnCount());
					if (spawnDistance > 1.0f)
					{
						checkFail("respawn did not return to the start");
					}
					else
					{
						// walk-in test of the win path: drop just before the
						// buddy on the goal platform
						checkBaseWins = game.getWinCount();
						game.teleportPlayer(Orkige::Vec3(36.0f, 3.0f, 0.0f));
						checkPhase = CheckPhase::WaitWin;
						checkPhaseDeadline = frameCount + 300;
					}
				}
				else if (frameCount >= checkPhaseDeadline)
				{
					checkFail("falling off never triggered a respawn");
				}
			}
			else if (selfCheck && !checkFailed &&
				checkPhase == CheckPhase::WaitWin)
			{
				// standing right in front of the goal, the HUD progress bar
				// must be near-full (screenshot the third such frame - the
				// framebuffer read can lag the simulation by one frame)
				if (hud.getProgress() > 80.0f)
				{
					++checkProgressFrames;
					if (checkProgressFrames == 3)
					{
						if (const char* progressShotPath = std::getenv(
							"ORKIGE_JUMPER_HUD_PROGRESS_SCREENSHOT"))
						{
							render->saveWindowContents(progressShotPath);
						}
					}
				}
				checkMaxProgress = std::max(checkMaxProgress,
					hud.getProgress());
				if (game.getWinCount() > checkBaseWins)
				{
					if (checkMaxProgress <= 80.0f)
					{
						checkFail("HUD progress bar never approached full "
							"in front of the goal");
					}
					// HUD: the win must have raised the banner this frame (the
					// hud update runs right after game.update); the progress
					// bar must have been near-full walking into the goal and
					// the title splash must be long gone (3s < the win frame)
					SDL_Log("jumper: selfcheck hud win - banner=%d title=%d",
						static_cast<int>(hud.isWinBannerVisible()),
						static_cast<int>(hud.isTitleVisible()));
					if (!hud.isWinBannerVisible())
					{
						checkFail("win did not show the HUD win banner");
					}
					else if (hud.isTitleVisible())
					{
						checkFail("HUD title splash never timed out");
					}
					else
					{
						checkPhase = CheckPhase::WaitBanner;
						checkPhaseDeadline = frameCount + 5;
					}
				}
				else if (frameCount >= checkPhaseDeadline)
				{
					checkFail("reaching the goal never triggered the win");
				}
			}
			else if (selfCheck && !checkFailed &&
				checkPhase == CheckPhase::WaitBanner)
			{
				// give the banner a few rendered frames, then optionally dump
				// a screenshot with the HUD visible and finish
				if (frameCount >= checkPhaseDeadline)
				{
					if (!hud.isWinBannerVisible())
					{
						checkFail("HUD win banner disappeared too early");
					}
					else
					{
						if (const char* hudShotPath =
							std::getenv("ORKIGE_JUMPER_HUD_SCREENSHOT"))
						{
							render->saveWindowContents(hudShotPath);
							SDL_Log("jumper: selfcheck hud screenshot -> %s",
								hudShotPath);
						}
						// camera-roll regression: the follow camera lookAt's
						// every frame of this whole session (plus respawn/
						// teleport jumps) - the engine's fixed yaw axis on
						// the camera node must have kept it roll-free (the
						// old shortest-arc lookAt slowly tilted the horizon)
						const float cameraRollDegrees = std::abs(
							cameraNode->getOrientation().getRoll()
								.valueDegrees());
						SDL_Log("jumper: selfcheck camera roll %.4f deg "
							"after the play session", cameraRollDegrees);
						if (cameraRollDegrees > 0.1f)
						{
							checkFail("follow camera accumulated roll");
						}
						else
						{
							SDL_Log("jumper: selfcheck complete - textures, "
								"movement (+%.2f m), jump (+%.2f m, %lu frames "
								"airborne), fall-respawn, the goal, the "
								"fastgui HUD and the roll-free camera all "
								"verified",
								checkMovedX, checkMaxRise,
								checkLandedFrame - checkJumpFrame);
							checkPhase = CheckPhase::Done;
							running = false;
						}
					}
				}
			}
			if (checkFailed)
			{
				exitCode = 1;
				running = false;
			}

			if (frameLimit != 0 && frameCount >= frameLimit)
			{
				running = false;
			}
		}

		if (selfCheck && !checkFailed && checkPhase != CheckPhase::Done)
		{
			SDL_Log("jumper: SELFCHECK FAILED - run ended in phase %d",
				static_cast<int>(checkPhase));
			exitCode = 1;
		}
		frameStats.logAtExit("jumper");
	}

	SDL_DestroyWindow(window);
	SDL_Quit();
	return exitCode;
}
