#!/usr/bin/env python3
"""Pack loose sprite PNGs into ONE atlas texture + a lean .oatlas region table
(stdlib only, deterministic, self-validating - the make_gui_atlas.py
structure applied to gameplay sprites).

    make_sprite_atlas.py <output_dir> <atlas_name> <sprite.png> [more.png ...]
    make_sprite_atlas.py --selftest

Output: <output_dir>/<atlas_name>.png + <output_dir>/<atlas_name>.oatlas.

.oatlas format (reuses the ConfigFile [Sprites] line grammar - a `texture`
line plus one `<region> <x> <y> <w> <h>` pixel-rect line per sprite; NOT .ogui,
which drags in font/whitepixel/kerning semantics this table does not need):

    # generated by Util/make_sprite_atlas.py - do not edit
    texture <atlas>.png
    <regionName> <x> <y> <w> <h>
    ...

SpriteComponent::loadSpriteFromAtlas(atlas, region) reads this table (through
the render facade's text-resource reader) and sets the sprite's UV rect from
the region pixel rect via the SHARED pixelRectToUV primitive (the same
half-texel inset the flipbook's frameToUVRect uses).

The script self-validates: it re-parses its own .oatlas with the engine's
whitespace-token rules, checks every region rect against the atlas bounds and
an occupancy grid (no overlaps), and confirms each region's pixels came from
its source sprite. Exits non-zero on any violation.

Region names are the sprite file basenames without extension (so ball.png ->
region "ball"). Determinism: sprites are packed in a fixed order (tallest
first, then by name) regardless of the argument order.
"""

import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import orkige_png  # noqa: E402  (sibling stdlib helper)

PADDING = 1  # transparent gutter around every sprite (bilinear seam safety)


def next_power_of_two(value):
    result = 1
    while result < value:
        result *= 2
    return result


def fail(message):
    print("make_sprite_atlas: VALIDATION FAILED - " + message, file=sys.stderr)
    sys.exit(1)


# --- packing ----------------------------------------------------------------

def pack(sprites):
    """shelf-pack (name, Image) sprites; returns (atlas Image, placements)
    where placements is a sorted list of (name, x, y, w, h)"""
    # deterministic order: tallest first (better shelves), then by name
    ordered = sorted(sprites, key=lambda s: (-s[1].height, s[0]))
    widest = max(image.width for _name, image in ordered)
    total_area = sum((image.width + PADDING) * (image.height + PADDING)
                     for _name, image in ordered)
    # a roughly square shelf width, at least wide enough for the widest sprite
    shelf_width = next_power_of_two(max(widest + 2 * PADDING,
                                        int(total_area ** 0.5)))
    placements = []
    cursor_x = PADDING
    cursor_y = PADDING
    shelf_height = 0
    for name, image in ordered:
        if cursor_x + image.width + PADDING > shelf_width:
            cursor_x = PADDING
            cursor_y += shelf_height + PADDING
            shelf_height = 0
        placements.append((name, cursor_x, cursor_y, image.width, image.height,
                           image))
        cursor_x += image.width + PADDING
        shelf_height = max(shelf_height, image.height)
    used_width = max(x + w + PADDING for _n, x, _y, w, _h, _img in placements)
    used_height = max(y + h + PADDING for _n, _x, y, _w, h, _img in placements)
    atlas = orkige_png.Image(next_power_of_two(used_width),
                             next_power_of_two(used_height))
    for _name, x, y, _w, _h, image in placements:
        atlas.blit(image, x, y)
    # drop the Image from the public placement tuples (name, x, y, w, h)
    table = sorted((name, x, y, w, h)
                   for name, x, y, w, h, _img in placements)
    return atlas, table


def build_atlas(out_dir, atlas_name, sprite_paths):
    sprites = []
    for path in sprite_paths:
        name = os.path.splitext(os.path.basename(path))[0]
        sprites.append((name, orkige_png.decode_png(path)))
    names = [name for name, _image in sprites]
    if len(set(names)) != len(names):
        fail("duplicate region names (sprite basenames must be unique)")
    atlas, table = pack(sprites)

    lines = ["# generated by Util/make_sprite_atlas.py - do not edit",
             "texture %s.png" % atlas_name]
    for name, x, y, w, h in table:
        lines.append("%s %d %d %d %d" % (name, x, y, w, h))

    png_path = os.path.join(out_dir, atlas_name + ".png")
    oatlas_path = os.path.join(out_dir, atlas_name + ".oatlas")
    orkige_png.encode_png(atlas, png_path)
    with open(oatlas_path, "w", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    return png_path, oatlas_path, atlas, dict(sprites), table


# --- self-validation --------------------------------------------------------

def parse_oatlas(path):
    """parse with the same whitespace-token rules SpriteComponent's loader and
    Ogre::ConfigFile use: first token is the key, comments start '#', section
    headers '[...]' are ignored"""
    texture = None
    regions = {}
    with open(path, "r") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("["):
                continue
            fields = line.split()
            if fields[0] == "texture":
                texture = fields[1]
            else:
                if len(fields) != 5:
                    fail("region line '%s' is not '<name> x y w h'" % line)
                regions[fields[0]] = tuple(int(v) for v in fields[1:])
    return texture, regions


def validate(png_path, oatlas_path, atlas, sources, table):
    texture, regions = parse_oatlas(oatlas_path)
    if texture != os.path.basename(png_path):
        fail("texture line '%s' does not match the atlas png" % texture)
    if set(regions) != set(sources):
        fail("region set does not match the input sprites")
    width, height = orkige_png.png_size(png_path)
    if (width, height) != (atlas.width, atlas.height):
        fail("atlas png size does not match the generated canvas")
    occupied = bytearray(width * height)
    for name, (x, y, w, h) in regions.items():
        if w <= 0 or h <= 0 or x < 0 or y < 0 or x + w > width or \
                y + h > height:
            fail("region '%s' is out of the atlas bounds" % name)
        source = sources[name]
        if (w, h) != (source.width, source.height):
            fail("region '%s' size %dx%d != source %dx%d"
                 % (name, w, h, source.width, source.height))
        for yy in range(y, y + h):
            row = yy * width
            for xx in range(x, x + w):
                if occupied[row + xx]:
                    fail("region '%s' overlaps another at %d,%d"
                         % (name, xx, yy))
                occupied[row + xx] = 1
        # the placed pixels must be the source pixels (corners suffice)
        for (sx, sy) in ((0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)):
            if atlas.get(x + sx, y + sy) != source.get(sx, sy):
                fail("region '%s' pixels do not match the source" % name)


# --- self-test (no external inputs; the packer's own ctest) -----------------

def selftest():
    with tempfile.TemporaryDirectory() as tmp:
        # a handful of solid-colour sprites of DIFFERENT sizes so packing,
        # shelving and the bounds/overlap checks all get exercised
        specs = [
            ("hero", 32, 48, (200, 40, 40, 255)),
            ("coin", 16, 16, (240, 220, 60, 255)),
            ("tile", 24, 24, (60, 160, 90, 255)),
            ("spark", 8, 40, (80, 120, 240, 255)),
            ("wide", 64, 12, (180, 90, 200, 255)),
        ]
        paths = []
        for name, w, h, colour in specs:
            image = orkige_png.Image(w, h,
                                     bytearray(bytes(colour) * (w * h)))
            path = os.path.join(tmp, name + ".png")
            orkige_png.encode_png(image, path)
            paths.append(path)
        png_path, oatlas_path, atlas, sources, table = build_atlas(
            tmp, "selftest_atlas", paths)
        validate(png_path, oatlas_path, atlas, sources, table)
        # re-run must be byte-identical (determinism regardless of arg order)
        png_b, oatlas_b, atlas_b, sources_b, table_b = build_atlas(
            tmp, "selftest_atlas2", list(reversed(paths)))
        validate(png_b, oatlas_b, atlas_b, sources_b, table_b)
        if table != table_b:
            fail("packing is not order-independent (non-deterministic)")
    print("make_sprite_atlas: self-test OK (%d sprites packed + validated)"
          % len(specs))


def main():
    if len(sys.argv) == 2 and sys.argv[1] == "--selftest":
        selftest()
        return
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(2)
    out_dir = sys.argv[1]
    atlas_name = sys.argv[2]
    sprite_paths = sys.argv[3:]
    os.makedirs(out_dir, exist_ok=True)
    png_path, oatlas_path, atlas, sources, table = build_atlas(
        out_dir, atlas_name, sprite_paths)
    validate(png_path, oatlas_path, atlas, sources, table)
    print("make_sprite_atlas: wrote %s + %s (%d regions, %dx%d, validated)"
          % (oatlas_path, png_path, len(table), atlas.width, atlas.height))


if __name__ == "__main__":
    main()
