/********************************************************************
	created:	Sunday 2026/07/12 at 18:00
	filename: 	MaterialAsset.h
	author:		steffen.roemer
	notice:		This source file is part of orkige (orkitec Game engine)
				For the latest info, see http://www.orkitec.com/
	copyright:	(c) 2009-2026 orkitec
*********************************************************************/
#ifndef __MaterialAsset_h__12_7_2026__18_00_00__
#define __MaterialAsset_h__12_7_2026__18_00_00__

//! @file MaterialAsset.h
//! @brief parser for the lean, agent-authorable `.omat` text asset
//! @remarks A `.omat` describes ONE surface look in the metal-rough PBS
//! vocabulary. Like `.oshape`, it is plain text an agent can write directly
//! over write_project_file, generated by `Util/*.py`, and parsed pure and
//! headless here (orkige_core, unit-tested without a renderer). The engine
//! side turns the parsed description into a renderer material through
//! `RenderSystem::createMaterial` (next = an HLMS PBS datablock; classic = a
//! Blinn-Phong approximation - see engine_render/RenderMaterial.h for the
//! per-backend capability statement).
//!
//! Grammar (v1), one directive per line, `#` starts a line comment:
//!   version 1                     optional; only version 1 is accepted
//!   albedo r g b a                base colour, straight RGBA 0..1
//!                                 (multiplies the albedo texture when both)
//!   albedoTexture NAME            resource name of the base-colour map
//!   metalness f                   0..1 (0 = dielectric, 1 = metal)
//!   roughness f                   0..1 (0 = mirror-smooth, 1 = fully rough)
//!   normalTexture NAME            tangent-space normal map
//!   emissive r g b                emitted colour (independent of lighting)
//!   emissiveTexture NAME          emissive map (tinted by `emissive`)
//!   alphaTest f                   cutout threshold 0..1 (0 = off, the
//!                                 default; texels whose albedo alpha falls
//!                                 below f are discarded - render AND shadow)
//!   twoSided 0|1                  1 = draw both faces (foliage/flag quads;
//!                                 default 0 = back faces culled)
//! Every directive is optional and may appear ONCE; defaults are a plain
//! white dielectric (albedo 1 1 1 1, metalness 0, roughness 1, no maps, no
//! emission, no alpha test, single-sided). Honest v1 boundaries: opaque or
//! CUTOUT only (alphaTest is binary keep/discard - no alpha BLENDING on
//! scene-content materials), no occlusion/specular maps, no per-texture UV
//! transforms, no reflection cubemap (image-based lighting arrives with the
//! sky/atmosphere surface - the hemisphere ambient is the current stand-in).
//! UNLIKE `.oshape` (which reserves future keywords), an unknown directive
//! is an ERROR - a typo silently ignored would misrender without a trace.

#include <core_util/String.h>

namespace Orkige
{
	//! @brief the `.omat` text -> surface-description front end (pure, headless)
	class MaterialAsset
	{
	public:
		//--- Types -------------------------------------------------
		//! a plain RGBA colour 0..1 (core-level - the engine converts to its
		//! render colour type; mirrors VectorTessellator's own colour struct)
		struct Colour
		{
			float r, g, b, a;
			Colour() : r(1.0f), g(1.0f), b(1.0f), a(1.0f) {}
			Colour(float red, float green, float blue, float alpha)
				: r(red), g(green), b(blue), a(alpha) {}
		};
		//! a parsed material: PBS parameters + texture resource names
		//! (defaults = a plain white dielectric)
		struct ParsedMaterial
		{
			Colour	albedo;					//!< base colour factor (default 1 1 1 1)
			String	albedoTexture;			//!< base-colour map resource name ("" = none)
			float	metalness = 0.0f;		//!< 0..1 metal-rough workflow
			float	roughness = 1.0f;		//!< 0..1 (1 = fully rough)
			String	normalTexture;			//!< tangent-space normal map ("" = none)
			Colour	emissive = Colour(0.0f, 0.0f, 0.0f, 1.0f);	//!< emitted colour
			String	emissiveTexture;		//!< emissive map ("" = none)
			float	alphaTest = 0.0f;		//!< cutout threshold 0..1 (0 = off)
			bool	twoSided = false;		//!< draw both faces (default: cull back)
		};

		//! @brief parse `.omat` text into a surface description.
		//! @return true on a well-formed material. On ANY malformation
		//! (unknown/duplicate directive, missing/garbage/trailing values,
		//! out-of-range scalar, unsupported version, empty text) it returns
		//! false, leaves @p out at the defaults and describes the problem in
		//! @p outError ("line N: ...") when one is passed - the honest
		//! "no material" fallback, never a crash.
		static bool parse(String const & text, ParsedMaterial & out,
			String * outError = NULL);

		//! @brief regenerate canonical `.omat` text from a parsed material -
		//! the clean-format inverse of parse(). Emits `version 1` then only the
		//! directives that differ from the defaults (a plain white dielectric
		//! serialises to just the version line), one per line in the header's
		//! declaration order, scalars trimmed to a short fixed form. The output
		//! round-trips: parse(serialize(m)) reproduces m. This is the editor's
		//! Apply path - the `.omat` is a generated-style asset, so a rewrite
		//! regenerates cleanly rather than preserving hand comments.
		static String serialize(ParsedMaterial const & material);
	};
}

#endif //__MaterialAsset_h__12_7_2026__18_00_00__
