#!/usr/bin/env python3
"""AtmosphereComponent end to end in the player - the scene-authored sky on
the running flavor, probed over captured pixels (projects/benchmark
fixture_atmo* scenes, generated by Util/make_benchmark_assets.py).

Four boots, one contract each:

  * fixture_atmo_control - the identical staging with NO component: the sky
    band shows the player's plain default background (the baseline).
  * fixture_atmo - an Environment with an enabled DAY AtmosphereComponent and
    NO scripts: the sky must arm purely from scene load (bright, blue-leaning
    band, clearly different from the control).
  * fixture_atmo_switch - EnvironmentA (day) owns at boot, EnvironmentB
    (night) is dormant; the driver script deactivates A at frame 80. The
    frame-60 capture shows day, the frame-130 capture must be MUCH darker -
    the take-over promotion changed the sky at runtime.
  * fixture_atmo_override - the Environment arms DAY, the driver's init arms
    the NIGHT look through engine:setAtmosphereBlend: the frame-60 capture
    must be night - a script's runtime drive WINS over the component base.

Pure stdlib (the shared PNG decoder). Runs per flavor.
Exit codes: 0 pass, 1 fail.
"""

import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from run_benchmark_pixel_test import decode_png, pixel  # noqa: E402

# the day band must be a real sky: bright and blue-leaning (both flavors'
# day looks clear these from the same side; the control/night bands cannot)
DAY_BAND_LUM_MIN = 50.0
# a meaningful change between two sky states (mean abs per-channel)
BAND_DIFF_MIN = 15.0
# the night band darkens by at least this much against the day band
NIGHT_DARKEN_MIN = 30.0


def log(msg):
    print("run_atmosphere_component_test: " + msg, flush=True)


def fail(msg):
    print("run_atmosphere_component_test: FAILED - " + msg, flush=True)
    sys.exit(1)


def sky_band(img):
    """mean (r, g, b) over the upper sky band (above the fixture props)"""
    width, height, channels, pixels = img
    total = [0.0, 0.0, 0.0]
    count = 0
    for y in range(int(height * 0.04), int(height * 0.30), 2):
        for x in range(0, width, 2):
            r, g, b = pixel(pixels, channels, width, x, y)
            total[0] += r
            total[1] += g
            total[2] += b
            count += 1
    return tuple(c / max(count, 1) for c in total)


def band_diff(a, b):
    return sum(abs(x - y) for x, y in zip(a, b)) / 3.0


def luminance(band):
    return sum(band) / 3.0


def run_player(args, scene, shot, frames, shot2=None, shot2_frame=None):
    for path in (shot, shot2):
        if path and os.path.exists(path):
            os.unlink(path)
    env = dict(os.environ)
    env.update({
        "ORKIGE_DEMO_FRAMES": str(frames),
        "ORKIGE_DEMO_SCREENSHOT": shot,
    })
    if shot2 is not None:
        env["ORKIGE_DEMO_SCREENSHOT2"] = shot2
        env["ORKIGE_DEMO_SHOT2_FRAME"] = str(shot2_frame)
    cmd = [args.player, "scenes/" + scene, "--project",
           os.path.join(args.repo, "projects/benchmark")]
    log("running: " + " ".join(cmd))
    result = subprocess.run(cmd, cwd=args.repo, env=env,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            timeout=480)
    output = result.stdout.decode("utf-8", "replace")
    if result.returncode != 0:
        log(output[-1500:])
        fail("player exited %d on %s" % (result.returncode, scene))
    if not os.path.exists(shot):
        fail("no screenshot written for " + scene)
    if shot2 is not None and not os.path.exists(shot2):
        fail("no second screenshot written for " + scene)
    return output


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--player", required=True)
    parser.add_argument("--dir", required=True)
    args = parser.parse_args()
    os.makedirs(args.dir, exist_ok=True)

    shot = lambda name: os.path.join(args.dir, name + ".png")

    # (1) control: no component, the plain default background
    run_player(args, "fixture_atmo_control.oscene", shot("control"), 100)
    control = sky_band(decode_png(shot("control")))

    # (2) the component boots the DAY sky with NO scripts
    run_player(args, "fixture_atmo.oscene", shot("day"), 100)
    day = sky_band(decode_png(shot("day")))
    log("sky bands: control %s, component day %s" % (
        ["%.1f" % c for c in control], ["%.1f" % c for c in day]))
    if band_diff(control, day) < BAND_DIFF_MIN:
        fail("the component scene's sky band matches the component-less "
             "control - the scene-authored atmosphere did not arm")
    # a DAY sky is BRIGHT and never warm-dominant (the next flavor's hazy
    # horizon reads near-white with a whisper of warmth, the classic dome a
    # clearer blue - the corridor bounds both from the same side; a night or
    # sunset band cannot clear it)
    if luminance(day) < DAY_BAND_LUM_MIN or day[2] < day[0] - 25.0:
        fail("the component sky band does not read as a day sky "
             "(lum %.1f, r %.1f, b %.1f)" % (luminance(day), day[0], day[2]))

    # (2b) the red-sky-on-load regression: the SAME enabled DAY Environment,
    # but authored BEFORE the Sun in file order (fixture_atmo_sunlast). The
    # sun's light registers directional - and the atmosphere resolves its sky -
    # before the sun's TransformComponent orients the node, so the load-time
    # apply reads an identity (horizon) sun and bakes a RED sky; with no script
    # to re-arm, only the frame-boundary sun re-resolve recovers it. The band
    # must read as a DAY sky (never red-dominant) and match the sun-first day
    # band closely - the load order must not change the result.
    run_player(args, "fixture_atmo_sunlast.oscene", shot("sunlast"), 100)
    sunlast = sky_band(decode_png(shot("sunlast")))
    log("sun-last band: %s (day %s)" % (
        ["%.1f" % c for c in sunlast], ["%.1f" % c for c in day]))
    if luminance(sunlast) < DAY_BAND_LUM_MIN or sunlast[2] < sunlast[0] - 25.0:
        fail("the sun-last scene shows a red/horizon sky on load - the "
             "atmosphere resolved its sun before the transform composed "
             "(lum %.1f, r %.1f, b %.1f)"
             % (luminance(sunlast), sunlast[0], sunlast[2]))
    if band_diff(day, sunlast) > NIGHT_DARKEN_MIN:
        fail("the sun-last day sky differs from the sun-first day sky - the "
             "scene-load order changed the atmosphere result (day %s, "
             "sun-last %s)" % (["%.1f" % c for c in day],
                               ["%.1f" % c for c in sunlast]))

    # (3) the switch: day at frame 60, promoted NIGHT by frame 130
    output = run_player(args, "fixture_atmo_switch.oscene",
                        shot("switch_day"), 160,
                        shot2=shot("switch_night"), shot2_frame=130)
    if "atmofixture: owner deactivated" not in output:
        fail("the switch driver never deactivated the owning Environment")
    before = sky_band(decode_png(shot("switch_day")))
    after = sky_band(decode_png(shot("switch_night")))
    log("switch bands: before %s, after %s" % (
        ["%.1f" % c for c in before], ["%.1f" % c for c in after]))
    if luminance(before) - luminance(after) < NIGHT_DARKEN_MIN:
        fail("deactivating the day owner did not hand the sky to the night "
             "instance (before lum %.1f, after lum %.1f)"
             % (luminance(before), luminance(after)))

    # (4) the override: the script's night beats the component's day at boot
    output = run_player(args, "fixture_atmo_override.oscene",
                        shot("override"), 100)
    if "atmofixture: override armed" not in output:
        fail("the override driver never armed its runtime look")
    override = sky_band(decode_png(shot("override")))
    log("override band: %s" % (["%.1f" % c for c in override],))
    if luminance(day) - luminance(override) < NIGHT_DARKEN_MIN:
        fail("the script's night override did not beat the component's day "
             "base (day lum %.1f, override lum %.1f)"
             % (luminance(day), luminance(override)))

    log("PASS - component boots the sky scriptlessly, activation promotes "
        "the next instance, a script override wins")
    return 0


if __name__ == "__main__":
    sys.exit(main())
