    if(MSVC)
        set(CMAKE_CXX_FLAGS_DEBUG_INIT "/MP4 /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1")
        set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "/MP4 /MD /O1 /Ob1 /D NDEBUG")
        set(CMAKE_CXX_FLAGS_RELEASE_INIT        "/MP4 /MD /O2 /Ob2 /D NDEBUG")
        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "/MP4 /MD /Zi /O2 /Ob1 /D NDEBUG")
    elseif(APPLE)
    	set(CMAKE_CXX_FLAGS_DEBUG_INIT "-Wno-overloaded-virtual -Wno-format -Wno-char-subscripts -Wno-logical-op-parentheses -Wno-implicit-function-declaration -Wno-bitwise-op-parentheses")
        set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "-Wno-overloaded-virtual -Wno-format -Wno-char-subscripts -Wno-logical-op-parentheses -Wno-implicit-function-declaration -Wno-bitwise-op-parentheses")
        set(CMAKE_CXX_FLAGS_RELEASE_INIT        "-Wno-overloaded-virtual -Wno-format -Wno-char-subscripts -Wno-logical-op-parentheses -Wno-implicit-function-declaration -Wno-bitwise-op-parentheses")
        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-Wno-overloaded-virtual -Wno-format -Wno-char-subscripts -Wno-logical-op-parentheses -Wno-implicit-function-declaration -Wno-bitwise-op-parentheses")
    endif()
